# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f76619b82bd05a127826d874bd82bece66d01adb2a28cd9a062d859fd1c103b3a1135835e39bfc469a28289c2648860fcc2bff7fbe575aec7e793dc027f82f7

test:
  secret_key_base: 1ce6cf57cc54e1137edb1a1bb73d1324a6988d3e9dc7058342fa9804e00b51b20f3ed02eedbd2a77ef62be225fab62a89141415ed39bf8f9a52f25af2e3708ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
